name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Enable Flutter Web
      run: flutter config --enable-web

    - name: Install dependencies
      run: flutter pub get
    
    - name: Build web
      run: flutter build web --release --base-href "/military-staff-shuttle/"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        force_orphan: true
        user_name: 'github-ci[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Publish to gh-pages'

  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: cedvdb/action-flutter-build-android@v1
      with:
        keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
        keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
        # optionals
        build-cmd: flutter build apk --release --flavor dev
        working-directory: ./

    - name: Archive APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        # Try running the build locally with the build command to be sure of this path
        path: build/app/outputs/flutter-apk/app-dev-release.apk
